baseURL = "https://midiario.ga/"
languageCode = "en-us"
title = "Mi diario"
theme = "webhosttheme"

[params]
  author = "Sponville"
  description = "Mi diario"

[taxonomies]
  categoria = "categorias"
  etiqueta = "etiquetas"